### ISSUE TITLE
multi node scenario "compute node + 4" is not enough 

### ISSUE THREAD

**Issue by Amir-Teshome** [pmorillon/xp5k-openstack#6]
The documentation states the total number of nodes used by the deployment is computes + 4. But I tried to deploy openstack by setting  "nodes  [computes + 4]" in xp.conf. It returns an error "Job #743758 require more nodes for required roles". then by making it nodes  [computes + 5] it works with out error. 

I tried multiple times assuming as if there is no resource for my jobs but it seems an error because it works with more resource. 

The full error out put

rake aborted!
Job #743758 require more nodes for required roles
/home/wamir/xp5k-openstack/.gem/gems/xp5k-0.0.12/lib/xp5k/role.rb:69:in `create_roles'
/home/wamir/xp5k-openstack/.gem/gems/xp5k-0.0.12/lib/xp5k/xp.rb:90:in`define_job'
scenarios/liberty_multinodes/tasks/scenario.rb:64:in `<top (required)>'
/home/wamir/xp5k-openstack/Rakefile:84:in`load'
/home/wamir/xp5k-openstack/Rakefile:84:in `block in <top (required)>'
/home/wamir/xp5k-openstack/Rakefile:83:in`each'
/home/wamir/xp5k-openstack/Rakefile:83:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by msimonin** [comment]
Hello, 

The following will reserve 6 nodes to deploy openstack  and use 2 as compute : 

```
╰─$ cat xp.conf
site              'rennes'
walltime          '3:00:00'
scenario          'liberty_multinodes'

# scenario specific
computes          2
```

corresponding code is here : https://github.com/pmorillon/xp5k-openstack/blob/master/scenarios/liberty_multinodes/tasks/scenario.rb#L24

**Comment by Amir-Teshome** [comment]
Hello, 

Thanks for the response. The error happens when I explicitly specify number of nodes in xp.conf file. I tried  with out specifying and it works with out error.

**Comment by pmorillon** [comment]
Just for information, you can not change computes number after the OAR job is started. You need to clean all with :

```
rake grid5000:clean
```

and restart.
